OdinCM/Pages/Articles/All.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdinCM.Data;
using OdinCM.Data.Data.Interfaces;
using OdinCM.Data.Models;

namespace OdinCM.Pages.Articles
{
    public class AllModel : PageModel
    {
        private readonly IArticleRepository  _articleRepo;
        

        public AllModel(IArticleRepository articleRepo)
        {
            _articleRepo = articleRepo;
        }

        [FromRoute]
        public int PageNumber { get; set; } = 1;


        [BindProperty]
        public int PageSize { get; set; } = 3;

        public SelectList PageSizeOptions { get; set; }

        public int TotalPages { get; set; }

        public IEnumerable<Article> Articles { get; set; }


        public async Task OnGet(int pageNumber = 1)
        {
            ManagePageSize();
            Articles = await _articleRepo.GetAllArticlesPaged(PageSize, pageNumber);
            TotalPages = await _articleRepo.GetTotalPagesOfArticles(PageSize);
        }

        private void ManagePageSize()
        {
            if (int.TryParse(Request.Cookies["PageSize"], out var pageSize)  == false)
            {
                pageSize = 20;
                Response.Cookies.Append("PageSize", pageSize.ToString());
            }

            var selectPageSizes = new List<int> { 2, 5, 10, 20, 40 };
            if (selectPageSizes.Contains(pageSize) == false)
            {
                selectPageSizes.Insert(0, pageSize);
            }
            PageSizeOptions = new SelectList(selectPageSizes);
            PageSize = pageSize;
        }

    }
}

OdinCM/Pages/Articles/ArticleNotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdinCM.Pages.Articles
{
    public class ArticleNotFoundModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

OdinCM/Pages/Articles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NodaTime;
using OdinCM.Data.Models;
using OdinCM.Helpers;
using Microsoft.Extensions.Logging;
using System.Security.Claims;
using OdinCM.Data;
using OdinCM.Data.Data.Interfaces;

namespace OdinCM.Pages.Articles
{
    public class CreateModel : PageModel
    {
        private readonly IArticleRepository _articleRepo;
        private readonly IClock _clock;
        public ILogger Logger { get; private set; }

        public CreateModel(IArticleRepository articleRepo, IClock clock, ILoggerFactory loggerFactory)
        {
            _articleRepo = articleRepo;
            _clock = clock;
            this.Logger = loggerFactory.CreateLogger("CreatePage");
        }

        public async Task<IActionResult> OnGetAsync(string slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return Page();
            }

            if (await _articleRepo.GetArticleBySlug(slug) != null)
            {
                return Redirect($"/Articles/{slug}/Edit");
            }


            Article = new Article()
            {
                Topic = UrlHelpers.SlugToTopic(slug)
            };

            return Page();
        }



        [BindProperty]
        public Article Article { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            var slug = UrlHelpers.URLFriendly(Article.Topic);
            if (string.IsNullOrWhiteSpace(slug))
            {
                ModelState.AddModelError("Article.Topic", "The Topic must contain at least one alphanumeric character.");
                return Page();
            }
          
            Article.Slug = slug;
            Article.AuthorId = Guid.Parse(this.User.FindFirstValue(ClaimTypes.NameIdentifier)); 

            if (!ModelState.IsValid)
            {
                return Page();
            }
  
            // Check if slug already exist in database
            Logger.LogWarning($"Creating page with slug: {slug}");
            

            if (await _articleRepo.IsTopicAvailable(slug, 0))
            {
                ModelState.AddModelError("Article.Topic", "This Title already exists.");
                return Page();
            }

            Article.Published = _clock.GetCurrentInstant();

            Article = await _articleRepo.CreateArticleAndHistory(Article);

            var articlesToCreateFromLinks = (await ArticleHelpers.GetArticlesToCreate(_articleRepo, Article, createSlug: true))
                .ToList();

            if (articlesToCreateFromLinks.Count > 0)
            {
                return RedirectToPage("CreateArticleFromLink", new { id = slug });
            }


            return Redirect($"/Articles/{Article.Slug}");
        }

    }
}

OdinCM/Pages/Articles/CreateArticleFromLink.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NodaTime;
using OdinCM.Helpers;
using OdinCM.Data.Models;
using OdinCM.Data.Data.Interfaces;

namespace OdinCM.Pages.Articles
{
    [Authorize]
    public class CreateArticleFromLinkModel : PageModel
    {
        [BindProperty]
        public Article Article { get; set; }
        [BindProperty]
        public List<string> LinksToCreate { get; set; } = new List<string>();

        private readonly IArticleRepository _articleRepo;
        private readonly IClock _clock;

        public CreateArticleFromLinkModel(IArticleRepository articleRepo, IClock clock)
        {
            _articleRepo = articleRepo;
            _clock = clock;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Article = await _articleRepo.GetArticleBySlug(id);

            if (Article == null)
            {
                return new ArticleNotFoundResult();
            }

            LinksToCreate = (await ArticleHelpers.GetArticlesToCreate(_articleRepo, Article)).ToList();

            if (LinksToCreate.Count == 0)
            {
                return Redirect($"/Articles/{(Article.Slug == "home-page" ? "" : Article.Slug)}");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostCreateLinksAsync(string slug)
        {
            foreach (var link in LinksToCreate)
            {
                var newArticle = new Article
                {
                    Slug = link,
                    Topic = link.ToTitleCase()
                                .RemoveHyphens(),
                    Published = _clock.GetCurrentInstant(),
                    Content = string.Empty
                };

                newArticle = await _articleRepo.CreateArticleAndHistory(newArticle);
            }

            return Redirect($"/Articles/{(slug == "home-page" ? "" : slug)}");
        }

        public IActionResult OnPostCancel(string slug)
        {
            return Redirect($"/Articles/{(slug == "home-page" ? "" : slug)}");
        }
    }
}

OdinCM/Pages/Articles/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OdinCM.Data.Models;
using OdinCM.Data;

namespace OdinCM.Pages.Articles
{
    [Authorize("CanDeleteArticles")]
    public class DeleteModel : PageModel
    {
        private readonly OdinCMContext _context;

        public DeleteModel(OdinCMContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Article Article { get; set; }

        public async Task<IActionResult> OnGetAsync(string slug)
        {
            if (slug == null)
            {
                return NotFound();
            }

            Article = await _context.Articles.SingleOrDefaultAsync(m => m.Slug == slug);

            if (Article == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string slug)
        {
            if (slug == null)
            {
                return NotFound();
            } 


            Article = await _context.Articles.SingleOrDefaultAsync(m => m.Slug == slug);

            if (Article != null)
            {
                _context.Articles.Remove(Article);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./All");
        }
    }
}

OdinCM/Pages/Articles/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OdinCM.Data.Models;
using OdinCM.Data;
using NodaTime;
using OdinCM.Helpers;
using Microsoft.AspNetCore.Authorization;
using SendGrid;
using SendGrid.Helpers.Mail;
using OdinCM.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.Extensions.Configuration;
using OdinCM.Services;
using Microsoft.AspNetCore.Identity.UI.Services;
using OdinCM.Data.Data.Interfaces;

namespace OdinCM.Pages.Articles
{
    
    public class DetailsModel : PageModel
    {
        private readonly IArticleRepository _articleRepo;
        private readonly ICommentRepository _commentRepo;
        private readonly ISlugHistoryRepository _slugHistoryRepo;
        private readonly IClock _clock;
        private readonly UserManager<CoreOdinUser> _userManager;
        private readonly INotificationService _notificationService;

        public IConfiguration Configuration { get; }
        public IEmailSender Notifier { get; }


        public DetailsModel(
            IArticleRepository articleRepo,
            ICommentRepository commentRepo,
            ISlugHistoryRepository slugHistoryRepo,
            UserManager<CoreOdinUser> userManager,
            IConfiguration config,
            IClock clock,
            INotificationService notificationService)
        {
            _articleRepo = articleRepo;
            _commentRepo = commentRepo;
            _slugHistoryRepo = slugHistoryRepo;
            _clock = clock;
            _userManager = userManager;            
            _notificationService = notificationService;
            Configuration = config;
        }

        public Article Article { get; set; }

        [ViewDataAttribute]
        public string Slug { get; set; }

        public async Task<IActionResult> OnGetAsync(string slug)
        {
            slug = slug ?? "home-page";

            Article = await _articleRepo.GetArticleBySlug(slug);              

            if (Article == null)
            {
                Slug = slug;
                var historical = await _slugHistoryRepo.GetSlugHistoryWithArticle(slug);

                if (historical != null)
                {
                    return new RedirectResult($"~/{historical.Article.Slug}");
                }
                else
                {
                    return new ArticleNotFoundResult(slug);
                }

            }

            if (Request.Cookies[Article.Topic] == null)
            {
                Article.ViewCount++;
                Response.Cookies.Append(Article.Topic, "foo", new Microsoft.AspNetCore.Http.CookieOptions
                {
                    Expires = DateTime.UtcNow.AddMinutes(5)
                });

            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Comment comment)
        {
            TryValidateModel(comment);
            Article = await _articleRepo.GetArticleByComment(comment);

            if (Article == null)
                return new ArticleNotFoundResult();

            if (!ModelState.IsValid)
                return Page();

            comment.Article = Article;

            comment.Submitted = _clock.GetCurrentInstant();

           
            var author = await _userManager.FindByIdAsync(Article.AuthorId.ToString());
            await _commentRepo.CreateComment(comment);
            await _notificationService.NotifyAuthorNewComment(author, Article, comment);

            
            return Redirect($"/Articles/{Article.Slug}");
        }
    }
}

OdinCM/Pages/Articles/Edit.cshtml.cs
using OdinCM.Data;
using OdinCM.Data.Data.Interfaces;
using OdinCM.Data.Data.Repositories;
using OdinCM.Data.Models;
using OdinCM.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NodaTime;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OdinCM.Pages.Articles
{
    public class EditModel : PageModel
    {
        
        private readonly IArticleRepository _articleRepo;
        private readonly ISlugHistoryRepository _slugRepo;
        private readonly IClock _clock;

        public EditModel( IArticleRepository articleRepo, ISlugHistoryRepository slugHistoryRepository, IClock clock)
        {
            _articleRepo = articleRepo;
            _slugRepo = slugHistoryRepository;
            _clock = clock;
        }

        [BindProperty]
        public Article Article { get; set; }

        public async Task<IActionResult> OnGetAsync(string slug)
        {
            if (slug == null)
            {
                return NotFound();
            }

            Article = await _articleRepo.GetArticleBySlug(slug);

            if (Article == null)
            {
                return new ArticleNotFoundResult();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var existingArticle = await _articleRepo.GetArticleById(Article.Id);
            Article.ViewCount = existingArticle.ViewCount;
            Article.Version = existingArticle.Version + 1;

            //check if the slug already exists in the database.  
            var slug = UrlHelpers.URLFriendly(Article.Topic);
            if (String.IsNullOrWhiteSpace(slug))
            {
                ModelState.AddModelError("Article.Topic", "The Topic must contain at least one alphanumeric character.");
                return Page();
            }

            if (await _articleRepo.IsTopicAvailable(slug, Article.Id))
            {
                ModelState.AddModelError("Article.Topic", "This Title already exists.");
                return Page();
            }

            // Verify if there are links to new articles
            var articlesToCreateFromLinks = (await ArticleHelpers.GetArticlesToCreate(_articleRepo, Article, createSlug: true)).ToList();

            
            Article.Published = _clock.GetCurrentInstant();
            Article.Slug = slug;
            Article.AuthorId = Guid.Parse(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            Article.AuthorName = User.Identity.Name;

            if (!string.Equals(Article.Slug, existingArticle.Slug, StringComparison.InvariantCulture))
            {
                await _slugRepo.AddToHistory(existingArticle.Slug, Article);
            }

            //AddNewArticleVersion();

            try
            {
                await _articleRepo.Update(Article);
            }
            catch (ArticleNotFoundException)
            {
                return new ArticleNotFoundResult();
            }

           
            if (articlesToCreateFromLinks.Count > 0)
            {
                return RedirectToPage("CreateArticleFromLink", new { id = slug });
            }


            return Redirect($"/Articles/{(Article.Slug == "home-page" ? "" : Article.Slug)}");
        }

       

    }
}

OdinCM/Pages/Articles/OldIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using OdinCM.Data;
using OdinCM.Data.Models;

namespace OdinCM.Pages.Articles
{
    public class IndexModel : PageModel
    {
        private readonly OdinCMContext _context;

        public IndexModel(OdinCMContext context)
        {
            _context = context;
        }

        public IList<Article> Article { get;set; }

        public async Task OnGetAsync()
        {
            Article = await _context.Articles.ToListAsync();
        }
    }
}

OdinCM/Pages/Articles/All.cshtml
@page "{PageNumber?}"
@model OdinCM.Pages.Articles.AllModel
@using Microsoft.AspNetCore.Mvc.Rendering
@{
    ViewData["Title"] = "All";
}


<h2>@Localizer["AllArticles"]</h2>

<p>
    <a asp-page="Create">New Suggestion</a>
</p>

<pager total-pages="Model.TotalPages" current-page="Model.PageNumber" page="All"></pager>




<div class="cwiki-flex-container">
    @foreach (var article in Model.Articles)
    {
        @await Html.PartialAsync("_ArticleRow", article)
    }
</div>
@section Styles {
    <style>
        .pageNumber {
            margin: 0px 4px;
        }

        .cwiki-flex-container {
            padding: 0;
            margin: 0;
            display: -webkit-box;
            display: -moz-box;
            display: -ms-flexbox;
            display: -webkit-flex;
            display: flex;
            -webkit-flex-flow: row wrap;
            justify-content: space-around;
        }

        .cwiki-flex-item {
            width: 360px;
            color: white;
            border-radius: 20px;
        }
    </style>
}

<script type="text/javascript">
    function UpdatePageSize(value) {
        document.cookie = encodeURIComponent("PageSize") + "=" + encodeURIComponent(value) + "; path=/";
    location = '/articles/all/1'; 
    }
</script>

OdinCM/Pages/Articles/ArticleNotFound.cshtml
@{
    var title = "Article not found";
    ViewData["Title"] = title;
}
<h1>@title</h1>

<ul>
    <li>@Localizer["ListItem1"]</li>
    <li>@Localizer["ListItem2"]</li>
    <li>@Localizer["ListItem3"] <a asp-page="/Create">create</a> the page?</li>
</ul>

<div>
    <a class="btn btn-outline-info" asp-page="/Articles/Create">@Localizer["Create"]</a>
</div>

<a href="~/">@Localizer["GoHome"]</a>

OdinCM/Pages/Articles/Create.cshtml
@page
@model OdinCM.Pages.Articles.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Article.Topic" class="control-label"></label>
                <input asp-for="Article.Topic" class="form-control" />
                <span asp-validation-for="Article.Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Article.Content" class="control-label"></label>
                <textarea asp-for="Article.Content" class="form-control"></textarea>
                <span asp-validation-for="Article.Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="input-group mb-3">
                   
                    <div class="input-group-prepend">
                        <span class="input-group-text">Upload</span>
                    </div>

                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" onchange="openFile(event)">
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Create</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @await Html.PartialAsync("_EditorScript")
}

@section Styles {
    @await Html.PartialAsync("_EditorStyle")
}

OdinCM/Pages/Articles/CreateArticleFromLink.cshtml
@page
@model OdinCM.Pages.Articles.CreateArticleFromLinkModel
@using OdinCM.Helpers
@{
    ViewData["Title"] = "CreateArticleFromLink";
}

<h2>Found links to articles that do not yet exist</h2>
<hr />
<br />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div>
                <div>The following links to CoreWiki articles that do not yet exist were found in the Article:</div>
                <br />
                @if (Model.LinksToCreate != null && Model.LinksToCreate.Count > 0)
                {
                    @for (var i = 0; i < Model.LinksToCreate.Count; i++)
                    {
                        <input asp-for="@Model.LinksToCreate[i]]" type="hidden" />
                        <span>* <b>@Model.LinksToCreate[i].ToTitleCase().RemoveHyphens()</b> (@Model.LinksToCreate[i])</span>
                        <br />
                    }
                }
            </div>
            <br />
            <div>Would you link to create these articles now?</div>
            <br />
            <div class="form-group">
                <input type="hidden" asp-for="Article.Slug" />
                <div class="input-group mb-3">
                    <button type="submit" class="btn btn-outline-primary" asp-page-handler="CreateLinks" asp-route-slug=@Model.Article.Slug>Yes</button>
                    <span>&nbsp;</span>
                    <button type="submit" class="btn btn-outline-primary" asp-page-handler="Cancel" asp-route-slug=@Model.Article.Slug>No</button>
                </div>
            </div>
        </form>
    </div>
</div>

OdinCM/Pages/Articles/Delete.cshtml
@page
@model OdinCM.Pages.Articles.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Article.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Article.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Article.Published)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Article.Published)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Article.Id" />
        <button type="submit" class="btn btn-outline-primary" asp-policy="CanDeleteArticle" asp-policy-message="You do not have permission to delete this article.">Delete</button>
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

OdinCM/Pages/Articles/Details.cshtml
@page "./Articles/{slug?}"
@model Articles.DetailsModel
@using OdinCM.Helpers
@{
    var title = Localizer["Details"];
    if (!string.IsNullOrEmpty(Model.Article.Topic))
    {
        ViewData["Title"] = Model.Article.Topic;
    }
    else
    {
        ViewData["Title"] = title;
    }
}

<div class="card card-header">
    <div class="container">
        <div class="row">
            <h2 class="col-xl-7 col-lg-8 col-md-12">@Model.Article.Topic</h2>
            <div class="col-xl-5 col-lg-4 col-md-12">
                <div class="container">
                    <div class="row">
                        <h5 class="col-xl-12 labelLastPublished">@Localizer["Published"]: <span data-value="@Model.Article.Published" class="timeStampValue"> @Model.Article.Published</span></h5>
                    </div>
                    <div class="row">
                        <h5 class="col-xl-4 labelViewCount ">@Localizer["ViewCount"]: <span data-value="@Model.Article.ViewCount"> @Model.Article.ViewCount</span></h5>
                        <h5 class="col-xl-8 labelEstReadTime">@Localizer["ReadingTime"]: <span class="duration" data-duration="@Model.Article.Content.CalculateReadTime().TotalMilliseconds"></span></h5>
                    </div>
                    <div class="row">
                        <h5 class="col-xl-12 labelViewCount"><a asp-page="History" asp-route-slug="@Model.Article.Slug">@string.Format(Localizer["HistoryFormat"].Value, Model.Article.Version) </a>   </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="container">
    <markdown markdown="Article.Content" />

    <div>
        <a asp-page="/Articles/Edit" asp-route-slug="@Model.Article.Slug" class="btn btn-outline-info">@Localizer["Edit"]</a>

        @if (Model.Article.Slug != "home-page")
        {
            <a href="~/" class="btn btn-secondary">@Localizer["GoHome"]</a>
        }
    </div>

    <partial name="_CommentsPartial" model="Model" />
</div>
@section Scripts {
    @await Html.PartialAsync("_EditorScript")
    <script type="text/javascript">
		$('.duration').each(function () {
			var duration = Number($(this).attr('data-duration'));
			$(this).text(moment.duration(duration).humanize());
		});
    </script>
}

@section Styles {
    @await Html.PartialAsync("_EditorStyle")
    <style>
        .labelDisplayName {
            font-weight: bold;
            text-transform: capitalize;
            color: #007bb8 !important;
        }

        .labelCommentedOn {
            color: #A6A6A6;
            font-size: 10px;
            height: 10px;
        }

        .labelLastPublished {
            font-size: .75em;
            padding-left: 1em;
            color: #a6a6a6;
        }

        .labelViewCount {
            font-size: .75em;
        }

            .labelViewCount > span {
                padding: 1px 4px 1px 4px;
                color: black;
                background-color: white;
                border-radius: 20px;
            }

        .labelEstReadTime {
            font-size: .75em;
        }

            .labelEstReadTime > span {
                padding: 1px 4px 1px 4px;
                color: black;
                background-color: white;
                border-radius: 20px;
            }
    </style>
}

OdinCM/Pages/Articles/Edit.cshtml
@page
@model OdinCM.Pages.Articles.EditModel

@{
   
    ViewData["Title"] = Localizer["Edit"];
}

<h2>@Localizer["Edit"]</h2>
<hr />
<br/>
<div class="row">
    <div class="col-md-8">
        <form method="post">
            <input type="hidden" asp-for="Article.Id" /> 
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Article.Topic" class="control-label"></label><br />
                <input asp-for="Article.Topic" class="form-control" />
                <span asp-validation-for="Article.Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Article.Content" class="control-label"></label>
                <textarea asp-for="Article.Content" class="form-control"></textarea>
                <span asp-validation-for="Article.Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" onchange="openFile(event)">
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Save</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Details">Back to Home</a>
</div>

@section Scripts {
    @await Html.PartialAsync("_EditorScript")
}

@section Styles {
    @await Html.PartialAsync("_EditorStyle")
}

OdinCM/Pages/Articles/OldIndex.cshtml
@page
@model OdinCM.Pages.Articles.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Suggestions</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Article[0].Topic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Article[0].Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Article[0].Published)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Article)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Topic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @item.Published
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Topic">Edit</a> |
                <a asp-page="./Details" asp-route-topicName="@item.Topic">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Topic">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

OdinCM/Pages/Articles/_EditorStyle.cshtml
   <link href="~/lib/simplemde/dist/simplemde.min.css" rel="stylesheet" />